src/components/checkout/Success.tsx
Adds a quote to a Flow State tweet in the message of the share button after a successful donation.
=> feat: add link to Flow State tweet in X share button

src/components/PoolCard.tsx, src/components/checkout/EditStream.tsx, src/components/checkout/Wrap.tsx
Adds help text clarifying the streams frequency and the necessity to wrap the token to make a donation.
=> feat: add help text on stream edit views

src/components/checkout/TopUp.tsx
Adds a link to a bridge in the top up step of the checkout flow
=> feat: add link to bridge in top up component

src/components/FlowStateCoreDetails.tsx, src/components/GranteeDetails.tsx, src/components/MatchingPoolDetails.tsx, src/components/MatchingPoolFunding.tsx, src/pages/core/index.tsx
Removes the user's current stream value shown in the header of the donation panel
=> feat: remove current stream value in recipient details components

package.json, pnpm-lock.yaml, src/pages/_app.tsx
Adds Posthog pageviews and session recordings
=> chore: add posthog

src/components/ConnectWallet.tsx, src/components/WalletBalance.tsx, src/components/checkout/Review.tsx, src/pages/_app.tsx, src/pages/core/index.tsx, src/pages/index.tsx, src/pages/pool/index.tsx, src/pages/privacy/index.tsx, src/pages/projects/[id].tsx, src/pages/projects/index.tsx
Obfuscate wallet address in Posthog session recordings
=> chore: obfuscate address in posthog

src/components/ConnectWallet.tsx, src/components/FlowStateCoreGraph.tsx, src/components/Layout.tsx, src/pages/core/index.tsx
Shows the graph in the core round page on mobile and opens the transaction panel on button click
=> feat: show viz in core round page on mobile

src/components/GranteeDetails.tsx, src/components/MatchingPoolDetails.tsx, src/components/PoolInfo.tsx, src/styles.scss
Adds markdown support for matching pool description
=> feat: add markdown support for matching pool description

src/app/home-page.tsx, src/components/PoolCard.tsx
Shows the matching multiplier of the round the project is in if the allocation and matching tokens are the same
=> feat: add matching multiplier in project page

src/components/checkout/TopUp.tsx, src/lib/networks.ts, src/types/network.ts
=> feat: change on ramp link in top up step

package.json, pnpm-lock.yaml
=> chore: update posthog sdk

src/app/flow-splitter/[chainId]/[poolId]/admin/admin.tsx, src/app/flow-splitter/components/BalancePlot.tsx, src/app/flow-splitter/flow-splitter.tsx
Shows the custom supertoken symbol in the flow splitter distribution stream transaction panel
=> fix: custom supertoken symbol in flow splitter checkout

src/app/flow-splitters/flow-splitters.tsx, src/app/flow-splitters/launch/launch.tsx
Adds a subtitle with links to `/flow-splitters`
=> feat: add subtitle with links to flow splitters page

src/app/flow-splitters/components/OpenFlow.tsx
Gets the supertoken balance with an RPC call instead of the subgraph in the flow splitter checkout
=> fix: get supertoken balance from contract instead of subgraph in flow splitter checkout

src/app/admin/configure/configure.tsx, src/app/flow-splitters/[chainId]/[poolId]/admin/admin.tsx, src/app/flow-splitters/[chainId]/[poolId]/flow-splitter.tsx, src/app/flow-splitters/components/InstantDistribution.tsx, src/app/flow-splitters/components/OpenFlow.tsx, src/app/flow-splitters/components/PoolGraph.tsx, src/app/flow-splitters/launch/launch.tsx, src/components/InfoTooltip.tsx, src/components/ProjectCreationModal.tsx, src/components/ProjectUpdateModal.tsx, src/types/gdaPool.ts
Adds instant distribution to flow splitter
=> feat: add instant distribution to flow splitter

src/app/flow-splitters/[chainId]/[poolId]/flow-splitter.tsx, src/app/flow-splitters/components/ActivityFeed.tsx, src/lib/networks.ts
Add activity feed in flow splitter public page
=> feat: add activity feed in flow splitter public page

src/app/flow-splitters/[chainId]/[poolId]/flow-splitter.tsx, src/app/flow-splitters/components/ActivityFeed.tsx, src/app/flow-splitters/components/PoolGraph.tsx
Adds ens names and avatars to flow splitter public page.
Queries the resolver in batch and build an hash table for performance.
=> feat: add ens name and avatar to flow splitter public page

src/app/admin/configure/configure.tsx, src/app/api/flow-state-eligibility/route.ts, src/app/pool/pool.tsx, src/components/GranteeDetails.tsx, src/components/GranteeFunding.tsx, src/components/WalletBalance.tsx, src/components/checkout/FlowStateEligibility.tsx, src/lib/networks.ts, src/types/network.ts
Adds a Flow State Managed option in the SQF launch page and an API to check Passport score & mint the eligibility NFT
=> feat: add flow state managed eligibility

package.json, pnpm-lock.yaml, src/app/api/mint-nft/route.ts, src/components/GranteeFunding.tsx, src/components/WalletBalance.tsx, src/components/checkout/FlowStateEligibility.tsx, src/components/checkout/MintNFT.tsx, src/components/checkout/NFTGating.tsx
Removes the Guild eligibility requirement to donate in a SQF round.
=> feat: remove guild eligibility requirement

src/components/GranteeFunding.tsx, src/components/MatchingPoolFunding.tsx, src/components/checkout/EditStream.tsx, src/components/checkout/FlowStateEligibility.tsx, src/components/checkout/MintNFT.tsx, src/components/checkout/NFTGating.tsx, src/components/checkout/Passport.tsx, src/components/checkout/TopUp.tsx, src/components/checkout/Wrap.tsx, src/lib/constants.ts
Enable direct donations to Flow State during the SQF checkout flow.
=> feat: enable direct flow state support via donations

src/app/flow-splitters/components/OpenFlow.tsx, src/components/GranteeFunding.tsx, src/components/MatchingPoolFunding.tsx, src/components/WalletBalance.tsx, src/components/checkout/SupportFlowState.tsx, src/hooks/superTokenBalanceOfNow.ts
Gets the Super Token balance at the time of the call from the contract instead of the subgraph.
=> fix: real time balance

src/components/checkout/Review.tsx
Adds a warning in the SQF stream review step if the liquidation would be closer than 2 days
=> feat: add close liquidation warning

src/app/core/core.tsx, src/app/flow-splitters/[chainId]/[poolId]/admin/admin.tsx, src/app/flow-splitters/[chainId]/[poolId]/flow-splitter.tsx, src/app/flow-splitters/components/PoolGraph.tsx, src/app/grantee/grantee.tsx, src/app/grantee/tools/tools.tsx, src/app/pool/pool.tsx, src/app/projects/[id]/project.tsx
Increase the amount of entities queried in the subgraph
=> fix: increase max subgraph entities queried

src/components/checkout/SupportFlowState.tsx
Adds suggested amount buttons to core support donations view
=> feat: add suggested amount buttons to core support donations view

src/app/admin/configure/configure.tsx
Adds link to request token support in SQF launch page
=> feat: add token support request link in SQF launch page

src/app/pool/components/StreamDeletionModal.tsx, src/components/WalletDashboard.tsx
Shows the stream to Flow State in the wallet dashboard of a token used in the matching pool
=> fix: matching pool token donation to flow state in wallet dashboard

src/lib/networks.ts
Adds the Flow State managed eligibility NFT contract addresses to the network config
=> chore: add managed eligibility NFT addresses

src/app/sqf/sqf.tsx
Add header and subtitle with links to `/sqf`
=> feat: add copy to SQF launch page

package.json, pnpm-lock.yaml, src/app/pool/components/PoolInfo.tsx, src/app/pool/components/Sankey.tsx, src/app/pool/page.tsx, src/app/pool/pool.tsx, src/styles.scss
Adds an animated Sankey diagram to the SQF pool info view
=> feat: add visualization to SQF pool info

src/app/pool/pool.tsx, src/app/sqf/sqf.tsx, src/components/GranteeFunding.tsx, src/components/MatchingPoolFunding.tsx, src/components/checkout/Success.tsx
Updates the text of the social shares on successful donation
=> feat: update text of social share on successful donation

src/app/sqf/configure/configure.tsx
Lowers registration start time for SQF on testnet
=> feat: lower registration start time for SQF on testnet

src/app/flow-councils/components/DistributionPoolFunding.tsx, src/app/flow-councils/components/distribution-pool-funding/Review.tsx, src/app/flow-councils/components/distribution-pool-funding/TopUp.tsx
Handles pure Super Tokens in Flow Councils
=> fix: pure supertokens in flow councils

src/app/flow-councils/components/GranteeCard.tsx, src/app/flow-councils/components/RoundBanner.tsx, src/app/flow-councils/components/Sidebar.tsx, src/app/flow-councils/grantee/grantee.tsx, src/app/flow-councils/launch/launch.tsx, src/app/flow-councils/membership/membership.tsx, src/app/flow-councils/review/review.tsx, src/app/grantee/components/Sidebar.tsx, src/app/grantee/grantee.tsx, src/app/grantee/tools/tools.tsx, src/app/sqf/components/Sidebar.tsx, src/app/sqf/configure/configure.tsx, src/app/sqf/matching/matching.tsx, src/app/sqf/pools/pools.tsx, src/app/sqf/review/review.tsx
Adds a button to show the sidebar on mobile in the SQF and Flow Councils admin pages
=> fix: mobile admin pages

src/app/flow-councils/[chainId]/[councilId]/flow-council.tsx, src/app/flow-councils/components/DistributionPoolDetails.tsx, src/app/flow-councils/components/GranteeCard.tsx, src/app/flow-councils/components/RoundBanner.tsx, src/app/flow-councils/components/distribution-pool-funding/Review.tsx, src/app/flow-councils/components/distribution-pool-funding/TopUp.tsx, src/app/flow-councils/components/distribution-pool-funding/Wrap.tsx, src/lib/utils.ts
Uses the number formatting browser API everywhere in Flow Councils voting UI
=> fix: flow councils number format

src/app/flow-councils/components/DistributionPoolFunding.tsx
Disable the distribution pool funding if no grantee has a vote. In case the flow was opened already the view is shown anyway to allow the distributor to close it
=> feat: disable flow council ditribution pool funding if zero votes

src/app/flow-councils/components/Sidebar.tsx, src/app/flow-councils/launch/launch.tsx, src/app/flow-councils/membership/membership.tsx, src/app/sqf/components/Sidebar.tsx
Adds a dropdown to chose council in admin sidebar
=> feat: add dropdown to chose council in admin sidebar

src/app/flow-councils/components/Sidebar.tsx, src/app/flow-councils/hooks/councilQuery.ts
Sorts the councils alphabetically in the admin sidebar
=> feat: sort councils alphabetically in admin sidebar

src/app/flow-councils/grantee/grantee.tsx, src/app/flow-councils/review/review.tsx
Adds a success icon to the SIWE button in Flow Council application and review step
=> feat: add success check mark on flow councils siwe button

src/app/flow-councils/components/Sidebar.tsx, src/app/flow-councils/membership/membership.tsx, src/lib/networks.ts
Adds validation of votes in flow councils membership page
=> feat: add votes number validation in flow councils membership page

src/app/flow-councils/components/Ballot.tsx
Changes the stepping increment from 10 to 1 in the ballot component of the Flow Councils voting UI
=> feat: change step amount of ballot in flow councils voting UI

src/app/flow-councils/components/Sidebar.tsx, src/app/flow-councils/flow-councils.tsx, src/app/flow-councils/grantee/grantee.tsx, src/app/flow-councils/launch/launch.tsx, src/app/flow-councils/membership/membership.tsx, src/app/flow-councils/permissions/page.tsx, src/app/flow-councils/permissions/permissions.tsx, src/app/flow-councils/review/review.tsx, src/lib/abi/council.ts, src/lib/networks.ts
Adds permissions page to Flow Councils
=> feat: add permissions page to flow councils

src/app/flow-councils/review/review.tsx
Fixes an issue that caused the profile metadata of a grantee application to be showed out of order on updates if the subgraph returned data sorted differently
=> fix: profiles in flow councils grantee review

src/app/flow-councils/hooks/allocationQuery.ts, src/lib/networks.ts
Updates Flow Councils subgraph endpoint
=> chore: update councils subgraph

src/app/core/components/OpenFlow.tsx
Adds a suggestion to claim rewards daily
=> feat: update claim help text

src/app/core/components/OpenFlow.tsx
Fixes an issue that caused the submit button to be enabled with 0 super token balance and 0 wrapping amount specified in the Core round flow opening view
=> fix: balance validation in core round flow opening view

src/app/api/mailinglist/route.ts, src/app/explore/components/RoundCard.tsx, src/app/explore/explore.tsx, src/components/Footer.tsx, src/lib/utils.ts, src/styles.scss
Adds mailing list signup on explorer page
=> feat: add mailing list signup on explorer page

src/app/explore/explore.tsx
Adds email validation message on explorer page
=> feat: add email validation message on explorer page

src/app/core/components/OpenFlow.tsx, src/app/core/core.tsx, src/app/flow-splitters/components/OpenFlow.tsx, src/app/pool/components/checkout/Review.tsx
Adds liquidation info on Flow Splitters checkout
=> feat: add liquidation info on flow splitters checkout

src/app/flow-guilds/[id]/flow-guild.tsx, src/app/flow-guilds/components/ActivityFeed.tsx, src/app/flow-guilds/components/DonateOnce.tsx, src/app/flow-guilds/components/Graph.tsx, src/app/flow-guilds/components/OpenFlow.tsx
Uses the same mobile layout for tablet on Flow Guilds
=> fix: flow guilds tablet layout

src/app/flow-councils/components/distribution-pool-funding/EditStream.tsx, src/app/flow-guilds/components/OpenFlow.tsx, src/app/flow-splitters/components/OpenFlow.tsx, src/app/pool/components/checkout/EditStream.tsx
Adds button to close stream in case the user has one open
=> feat: add button to close stream

src/app/explore/explore.tsx, src/app/explore/page.tsx, src/app/flow-guilds/lib/flowGuildConfig.ts
Changes default token for greenpilldevguild to ETHx
=> feat: change default token for greenpilldevguild

src/app/flow-councils/components/DistributionPoolFunding.tsx, src/app/flow-councils/components/distribution-pool-funding/EditStream.tsx, src/app/flow-councils/components/distribution-pool-funding/Review.tsx, src/app/flow-councils/components/distribution-pool-funding/TopUp.tsx, src/app/flow-guilds/components/OpenFlow.tsx, src/app/flow-splitters/components/OpenFlow.tsx, src/app/pool/components/GranteeFunding.tsx, src/app/pool/components/MatchingPoolFunding.tsx, src/app/pool/components/checkout/EditStream.tsx, src/app/pool/components/checkout/Review.tsx, src/app/pool/components/checkout/Success.tsx, src/app/pool/components/checkout/TopUp.tsx, src/app/pool/components/checkout/Wrap.tsx
Replace the liquidation warning mention of "wrap" with "deposit" for Pure Super Tokens
=> fix: pure supertoken liquidation warning text

src/app/flow-councils/grantee/grantee.tsx, src/app/grantee/components/Sidebar.tsx, src/app/grantee/grantee.tsx, src/app/projects/projects.tsx
Ignores projects with empty metadata
=> fix: do not show projects with empty metadata

src/app/api/good-dollar/eligibility/route.ts, src/app/flow-councils/components/Sidebar.tsx, src/app/gooddollar/components/RoundBanner.tsx, src/app/gooddollar/good-dollar.tsx
Adds an API to add eligible council members to the Good Dollar round
=> feat: add good dollar round api

package.json, pnpm-lock.yaml, src/app/api/flow-council/db.ts, src/app/api/good-dollar/sup/route.ts, src/app/gooddollar/components/Ballot.tsx, src/app/gooddollar/components/DistributionPoolDetails.tsx, src/app/gooddollar/components/DistributionPoolFunding.tsx, src/app/gooddollar/components/FlowCouncilWallet.tsx, src/app/gooddollar/components/GranteeCard.tsx, src/app/gooddollar/components/RoundBanner.tsx, src/app/gooddollar/components/distribution-pool-funding/EditStream.tsx, src/app/gooddollar/components/distribution-pool-funding/Review.tsx, src/app/gooddollar/components/distribution-pool-funding/Success.tsx, src/app/gooddollar/components/distribution-pool-funding/TopUp.tsx, src/app/gooddollar/components/distribution-pool-funding/Wrap.tsx, src/app/gooddollar/good-dollar.tsx, src/app/gooddollar/lib/councilConfig.ts, src/app/gooddollar/membership/membership.tsx, src/app/gooddollar/page.tsx, src/app/gooddollar/review/review.tsx, src/context/FlowCouncil.tsx, src/lib/networks.ts
Adds an API to assign points for SUP distribution for the Good Dollar round
=> feat: add good dollar sup api

src/app/api/good-dollar/sup/distribution/route.ts, src/app/gooddollar/lib/councilConfig.ts, vercel.json
Adds a cron job to update points assigned based on the total amount steamed to the distribution pool of the Good Dollar round
=> feat: add good dollar distribution pool sup

src/app/flow-councils/[chainId]/[councilId]/flow-council.tsx, src/app/flow-councils/components/GranteeCard.tsx, src/app/flow-councils/components/VoteBubble.tsx, src/app/flow-councils/hooks/animateVoteBubble.ts, src/app/gooddollar/good-dollar.tsx
Adds bounce animation on project added to ballot in Flow Councils
=> feat: add bounce animation on project added to ballot in flow councils

src/app/flow-councils/[chainId]/[councilId]/flow-council.tsx, src/app/flow-councils/components/Ballot.tsx, src/app/flow-councils/components/FlowCouncilWallet.tsx, src/app/flow-councils/components/GranteeCard.tsx, src/app/flow-councils/components/GranteeDetails.tsx, src/app/flow-councils/components/VoteBubble.tsx, src/app/flow-councils/hooks/council.ts, src/app/flow-councils/hooks/councilQuery.ts, src/app/gooddollar/components/Ballot.tsx, src/app/gooddollar/components/RoundBanner.tsx, src/app/gooddollar/good-dollar.tsx, src/context/FlowCouncil.tsx
Remove ballot showing flag from allocation reducer
=> fix: remove ballot showing flag from new allocation reducer

src/app/flow-councils/hooks/councilQuery.ts, src/app/flow-councils/membership/membership.tsx, src/app/gooddollar/membership/membership.tsx
Increases the query limit for council members
=> fix: council members query

src/app/flow-councils/membership/membership.tsx, src/app/flow-splitters/components/OpenFlow.tsx, src/app/gooddollar/membership/membership.tsx, src/lib/networks.ts
Allows submission of flow distributions with a warning if zero native balance so smart wallet can still propose the transaction
=> fix: allow submission of flow distributions with a warning if zero native balance

src/app/flow-councils/components/GranteeDetails.tsx
Adds grantee address to details view in Flow Councils
=> feat: add grantee address to details view in flow councils

src/app/api/good-dollar/sup/route.ts, src/app/flow-councils/[chainId]/[councilId]/flow-council.tsx, src/app/flow-councils/components/Ballot.tsx, src/app/flow-councils/components/FlowCouncilWallet.tsx, src/app/flow-councils/components/GranteeDetails.tsx, src/app/flow-councils/flow-councils.tsx, src/app/flow-councils/grantee/grantee.tsx, src/app/flow-councils/hooks/allocationQuery.ts, src/app/flow-councils/hooks/council.ts, src/app/flow-councils/hooks/councilMemberQuery.ts, src/app/flow-councils/hooks/councilQuery.ts, src/app/flow-councils/review/review.tsx, src/app/gooddollar/components/Ballot.tsx, src/app/gooddollar/good-dollar.tsx, src/app/gooddollar/grantee/grantee.tsx, src/app/gooddollar/review/review.tsx, src/context/FlowCouncil.tsx, src/lib/networks.ts
Adds funding stats to grantee details view in Flow Councils
=> feat: add funding stats to grantee details view in flow councils

src/app/flow-councils/membership/membership.tsx, src/app/gooddollar/membership/membership.tsx, src/lib/apollo.ts, src/lib/networks.ts
Paginates council members query results so that we can show more than 1000 at once
=> fix: council members pagination
