src/components/checkout/Success.tsx
Adds the link to the grantee frame in the Warpcast share message with the `embed[]=` query parameter so that a preview of the frame is correctly renderer when the user post
=> fix: frames link embed

src/components/GranteeFunding.tsx, src/components/MatchingPoolFunding.tsx, src/components/checkout/EditStream.tsx, src/components/checkout/Review.tsx, src/pages/core/index.tsx
Removes the ability to choose the time period based on which the flow rate is calculated and always uses a monthly time period.
=> feat: remove time period dropdown and use month by default in edit stream view

src/components/GranteeFunding.tsx, src/components/MatchingPoolFunding.tsx, src/components/checkout/Wrap.tsx
Adds text showing the remaining balance after the transaction under the input value of the wrapping step
=> feat: add remaining balance after wrap text in wrapping step

src/components/WalletBalance.tsx
Keeps the eligibility button in the wallet panel enabled with the primary color as background
=> fix: eligibility button color in wallet panel

src/app/flow-splitter/components/BalancePlot.tsx, src/app/flow-splitter/components/OpenFlow.tsx
Excludes the incoming flow rate resulting from disconnected units in a pool from the total flow rate in the flow splitter checkout because it's not used for liquidation purposes at the protocol level
=> fix: exclude flow rate from disconnected units from total flow rate in flow splitter checkout

src/app/flow-splitters/[chainId]/[poolId]/admin/admin.tsx, src/app/flow-splitters/flow-splitters.tsx
When a user uploads a .csv on the flow splitter admin page compare the diff between the new list and the existing pool members and zero out the ones not present
=> feat: zero out units of flow splitter members not present in csv

src/app/flow-splitters/components/OpenFlow.tsx
Enables the button in the Flow Splitters checkout to distribute a flow when the user has no balance while requiring wrapping.
fixes #55
=> fix: flow splitters open flow submission check

src/app/flow-splitters/components/OpenFlow.tsx
Waits for the new flow rate value from the subgraph before updating the amount input field in the flow distribution view of flow splitters
fixes #57
=> fix: flow splitters current flow rate input field update

src/app/flow-splitters/components/InstantDistribution.tsx, src/app/flow-splitters/components/OpenFlow.tsx
Handle underlying tokens with different decimals than 18 in the Flow Splitters checkout flow
=> fix: underlying token decimals on flow splitters

src/app/flow-councils/flow-councils.tsx
Use the connected chain id to get the graphQL client for the Superfluid subgraph
=> fix: network used for subgraph query in flow councils page

src/app/flow-councils/[chainId]/[councilId]/flow-council.tsx, src/app/flow-councils/hooks/gdaPoolQuery.ts
Adds a modal shown when the user is a grantee unconnected to the distribution pool prompting to connect
=> feat: add pool connection modal for unconnected grantees in flow councils

src/app/flow-councils/components/DistributionPoolDetails.tsx, src/app/flow-councils/components/DistributionPoolFunding.tsx
Builds the transactions array before the effects run in Flow Councils pool distribution funding so that if the wrapping step is skipped the submit button doesn't show a transaction too much for a bit
=> fix: build transactions array before effect in flow councils pool distribution funding

src/app/flow-councils/review/review.tsx
Fixes width of application link in Flow Councils review page so that it doesn't overflow on mobile
=> fix: mobile application link in flow councils review page

src/app/flow-councils/grantee/grantee.tsx
Places the network and token element on a new line in the Flow Councils grantee application page
=> fix: alignment of network and token in flow councils grantee application page

src/app/flow-councils/components/DistributionPoolDetails.tsx, src/app/flow-councils/components/DistributionPoolFunding.tsx, src/app/flow-councils/membership/membership.tsx
Another query was overwriting the cache resulting in an empty pool distributors array after an user closed the stream and the distribution pool details showing an incorrect value
=> fix: user total distributed in flow council pool details

src/app/flow-councils/flow-councils.tsx, src/app/flow-councils/review/review.tsx
Checks the transaction receipt for a success status before writing to the database in Flow Council applications review page
=> fix: transaction success check

src/app/flow-councils/[chainId]/[councilId]/flow-council.tsx, src/app/flow-councils/components/Sidebar.tsx, src/app/flow-councils/flow-councils.tsx, src/app/flow-councils/grantee/grantee.tsx, src/lib/constants.ts
Adds default name and description to Flow Councils to show when they don't have metadata
=> feat: add default metadata to councils

src/lib/networks.ts
Updates Flow Councils factory address with new one including fix to an issue that caused the flow to stop when the only council member changed votes
=> chore: update council factory address

src/app/flow-guilds/components/OpenFlow.tsx
Updates the user prompt for SUP rewards to include the $1 minimum volume threshold
=> fix: update SUP prompt with $ minimum

src/app/flow-guilds/components/OpenFlow.tsx, src/app/flow-splitters/components/OpenFlow.tsx
Keeps the color of the balance until an amount is entered in the Flow Splitters checkout
=> fix: flow splitters checkout balance validation color

src/app/flow-splitters/[chainId]/[poolId]/flow-splitter.tsx, src/app/flow-splitters/launch/launch.tsx
Shows a "Flow Splitter Not Found" message when the subgraph responds with a null `pools`
=> fix: flow splitter not found
